### ISSUE TITLE
LSU Modal

### ISSUE THREAD

**Issue by tonyhensler** [lon-yang/angularx-semantic-ui#1]
We are currently getting the following error when implementing the modal:-

Can't bind to 'active' since it isn't a known property of 'lsu-modal'.

**Comment by lon-yang** [comment]
Yeah, I think i missed this input parameter, this will be fixed in today, thanks


Best regards
--------------------------
Lon Yang
Email: dove2580@live.com<mailto:dove2580@live.com>

Tony Hensler <notifications@github.com> 于 2017年11月20日 下午11:32写道：


We are currently getting the following error when implementing the modal:-

Can't bind to 'active' since it isn't a known property of 'lsu-modal'.

―

**Comment by lon-yang** [comment]
I have published `0.0.2` version to solve this issue
